### ISSUE TITLE
LoadError: Error relocating .../libonesdk_shared.so: __vsnprintf_chk: symbol not found

### ISSUE THREAD

**Issue by deneor** [Dynatrace/OneAgent-SDK-Ruby-Sample-Binding#1]
How to reproduce:
* clone this repo (https://github.com/deneor/OneAgent-SDK-Ruby-Sample-Binding.git #load-error)
* `git submodule init && git submodule update`
* `docker build -t oneagent_sdk .`
* `docker run --rm -it oneagent_sdk`
* `require_relative 'oneagentsdk'`

Error:
```
irb(main):001:0> require_relative 'oneagentsdk'
Traceback (most recent call last):
        8: from /usr/local/bin/irb:11:in `<main>'
        7: from (irb):1
        6: from (irb):1:in `require_relative'
        5: from /oneagentsdk.rb:25:in `<top (required)>'
        4: from /oneagentsdk.rb:29:in `<module:OneAgentSdk>'
        3: from /usr/local/bundle/gems/ffi-1.10.0/lib/ffi/library.rb:99:in `ffi_lib'
        2: from /usr/local/bundle/gems/ffi-1.10.0/lib/ffi/library.rb:99:in `map'
        1: from /usr/local/bundle/gems/ffi-1.10.0/lib/ffi/library.rb:145:in `block in ffi_lib'
LoadError (Could not open library './OneAgent-SDK-for-C/lib/linux-x86_64/libonesdk_shared.so': Error relocating ./OneAgent-SDK-for-C/lib/linux-x86_64/libonesdk_shared.so: __vsnprintf_chk: symbol not found)
```

Any guesses, how to fix it?

**Comment by arminru** [comment]
Hi deneor!

According to your Dockerfile your setup is based on the image `ruby:2.5.3-alpine3.9`. Unfortunately, the underlying OneAgent SDK for C used by the Ruby binding does not support *musl libc* which is used by Alpine Linux. Please see the requirements stated here: https://github.com/Dynatrace/OneAgent-SDK-for-C#requirements
I've adapted your Dockerfile to use Debian and followed the steps you've described, with this configuration it works well:

```
FROM ruby:2.5.3-stretch

RUN apt-get update && apt-get install -y build-essential

ADD  /Gemfile* ./
RUN bundle install

ADD . .
CMD ["irb"]
```

Best,
Armin

**Comment by arminru** [comment]
I updated the link in the readme to the requirements as mentioned above.
If you have any other questions, feel free to open a new issue.
